### ISSUE TITLE
Add `--compressed` to default

### ISSUE THREAD

**Issue by vvb2060** [curl/wcurl#11]
I think it should be the default

**Comment by samueloph** [comment]
From curl's manpage:
> Response headers are not modified when saved, so if they are "in‐
              terpreted" separately again at a later point they might appear to
              be saying that the content is (still) compressed; while  in  fact
              it has already been decompressed.
> If this option is used and the server sends an unsupported encod‐
              ing,  curl reports an error. This is a request, not an order; the
              server may or may not deliver data compressed.
              
I'm not sure it's a good idea to set this by default, it can lead to errors if the encoding is not supported.

It will also cause issues if the user is trying to download a compressed file and wants to store it that way. I haven't tested it but it seems like curl would decompress the file in that case.
             
Do you always have a need to set that flag and have you never faced a need to store the file as compressed by the server?

With wcurl 2024-07-07, you can still accomplish this by `wcurl --curl-options="--compressed" $URL`. The goal of wcurl is to not require the user to set any flags, but you might find it easier to do this with wcurl than with curl.

With that version, you can also use the flag `--dry-run` to have wcurl output the curl invocation command and its arguments, without actually making the call. I hope this is useful in case you ever need to review the flags and possibly use curl directly.
