### ISSUE TITLE
Two different license files

### ISSUE THREAD

**Issue by ryandesign** [curl/wcurl#20]
There are now two different curl license files: the original one at [LICENSE](https://github.com/curl/wcurl/blob/main/LICENSE) and the newly added one at [LICENSES/curl.txt](https://github.com/curl/wcurl/blob/main/LICENSES/curl.txt). It should be possible to have a single license file that satisfies both REUSE requirements and allows GitHub to identify and display the license, in which one of these files is a symlink to the other. I forget which direction the symlink needs to be made to make both parties happy but I have seen it done in another repository.

**Comment by samueloph** [comment]
I've tried symlinks both ways and neither worked 100%:
`ln -s LICENSE LICENSES/curl.txt`
https://github.com/samueloph/wcurl?tab=License-1-ov-file - Doesn't show the license, only the name of the license file

`ln -s LICENSES/curl.txt LICENSE`
https://github.com/curl/wcurl/actions/runs/10336819570/job/28612972401 - Fails the REUSE compliance check.

**Comment by ryandesign** [comment]
According to https://github.com/ansible-community/community-topics/issues/112#issuecomment-1164756911, having the real file be the top-level COPYING (or LICENSE) file (so that GitHub can detect the license) and having a symlink to it in the LICENSES directory (for REUSE) should have worked. If this failed the REUSE compliance check, then the REUSE compliance check should be fixed.
