### ISSUE TITLE
versioned releases?

### ISSUE THREAD

**Issue by bagder** [curl/wcurl#26]
I think it would be beneficial to start doing wcurl releases using classical [semver](https://semver.org/) versions, and then also to mark them as releases here on GitHub so that the release feature works as people might expect.

**Comment by bagder** [comment]
I can live with calver, I just personally prefer semver. Especially if a long time might pass between releases as then the date risk start feeling old.

> If/when we decide to switch over to semver, this would require starting with some number that's higher than 2024.

IMHO, I think that if you would switch over now or soon, it could be okay to go down to 0.x or 1.x as this is still early days in wcurl time. I think we can accept some leeway and "trying out things" in the tool's childhood.

**Comment by samueloph** [comment]
> IMHO, I think that if you would switch over now or soon, it could be okay to go down to 0.x or 1.x as this is still early days in wcurl time. I think we can accept some leeway and "trying out things" in the tool's childhood.

Unfortunately there's no turning back for any who have shipped wcurl already, if we switch to semver and start with something lower than 2024, those who already ship wcurl will have to implement workarounds such as epochs (e.g.: prepending `1:` to the version string).

In hindsight, seems like it's a good idea to always prepend calver with `0.` to allow a seamless change to semver, but it's too late now.

I'll discuss this with @sergiodj in our weekly call this Thursday.

**Comment by sergiodj** [comment]
I don't have a strong preference here, but I tend to like semver better, too.  I think calver makes a lot of sense when your software release schedule is calendar-oriented, which is not our case here.

OTOH, as @samueloph said, now that we have already released wcurl using calver *and* given the fact that we don't really expect to have a lot of releases for the project (for now), maybe it just makes sense to stick with this versioning scheme.

When we rewrite wcurl in C using libcurl, then I believe we should just bite the bullet and switch to semver.

**Comment by classabbyamp** [comment]
as a downstream distributor (linux distro), switching sooner rather than later will make the transition easier, especially for package manages that don't have the capability to go "backwards" in versions (be that reverts, epoch, or other mechanism)

**Comment by samueloph** [comment]
We will not change the versioning scheme, we will stick to calver to avoid any issues for those who already ship wcurl as its own package.

I will close this issue once I do start using the "releases" feature of GitHub, which should happen on this weekend.

**Comment by samueloph** [comment]
We now have a GitHub release at https://github.com/curl/wcurl/releases and we'll keep using that moving forward.
